// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNJWbs6HWetyt2DzxLFZIf6M4LuSAb22k',
    appId: '1:1095379077848:web:329334ca258cf248f825ad',
    messagingSenderId: '1095379077848',
    projectId: 'pitik-1ad2d',
    authDomain: 'pitik-1ad2d.firebaseapp.com',
    databaseURL: 'https://pitik-1ad2d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pitik-1ad2d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpCsQh2oLsD_NdY2XJrF8AY3bAGSxVp4k',
    appId: '1:1095379077848:android:d3b6532e017f26abf825ad',
    messagingSenderId: '1095379077848',
    projectId: 'pitik-1ad2d',
    databaseURL: 'https://pitik-1ad2d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pitik-1ad2d.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDndGgn9oy_lR-LkmQoR3J2Spe2mc5yWJs',
    appId: '1:1095379077848:ios:896698d59afbef3cf825ad',
    messagingSenderId: '1095379077848',
    projectId: 'pitik-1ad2d',
    databaseURL: 'https://pitik-1ad2d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pitik-1ad2d.firebasestorage.app',
    iosBundleId: 'com.example.pitikApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDndGgn9oy_lR-LkmQoR3J2Spe2mc5yWJs',
    appId: '1:1095379077848:ios:896698d59afbef3cf825ad',
    messagingSenderId: '1095379077848',
    projectId: 'pitik-1ad2d',
    databaseURL: 'https://pitik-1ad2d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pitik-1ad2d.firebasestorage.app',
    iosBundleId: 'com.example.pitikApp',
  );
}
